{"name": "test_successful_login_and_logout", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 10000ms exceeded.\n=========================== logs ===========================\nwaiting for navigation to \"**https://liner.dstepanyuk.dev.smte.am/office/*\" until 'load'\n============================================================", "trace": "self = <tests.test_auth.TestAuthentication object at 0x0000012E87A92110>\npage = <Page url='https://liner.dstepanyuk.dev.smte.am/public/assets/js/libs/wavesurfer.timeline.js.map?'>\nconfig = {'apiUrl': 'https://liner.dstepanyuk.dev.smte.am/api/', 'baseUrl': 'https://liner.dstepanyuk.dev.smte.am/auth/', 'brow...password': 'wrong_password'}, 'valid_user': {'email': 'dstepanyuk@southmedia.io', 'password': 'yND-jC2-rWz-qqJ'}}, ...}\n\n    @allure.story(\"Successful login and logout\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_successful_login_and_logout(self, page, config):\n        \"\"\"Проверка успешной авторизации и выхода из системы\"\"\"\n        login_page = LoginPage(page, config.get(\"baseUrl\"))\n    \n        with allure.step(\"Переход на страницу логина\"):\n            login_page.navigate()\n    \n        with allure.step(\"Ввод учетных данных и вход\"):\n            valid_credentials = config['credentials']['valid_user']\n            login_page.login(valid_credentials['email'], valid_credentials['password'])\n    \n        with allure.step(\"Проверка успешной авторизации\"):\n            expected_url = \"https://liner.dstepanyuk.dev.smte.am/office/\"\n>           page.wait_for_url(f\"**{expected_url}*\", timeout=10000)\n\ntests\\test_auth.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9161: in wait_for_url\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py:575: in wait_for_url\n    return await self._main_frame.wait_for_url(**locals_to_params(locals()))\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:233: in wait_for_url\n    async with self.expect_navigation(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_event_context_manager.py:33: in __aexit__\n    await self._future\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    async def continuation() -> Optional[Response]:\n>       event = await waiter.result()\nE       playwright._impl._errors.TimeoutError: Timeout 10000ms exceeded.\nE       =========================== logs ===========================\nE       waiting for navigation to \"**https://liner.dstepanyuk.dev.smte.am/office/*\" until 'load'\nE       ============================================================\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:207: TimeoutError"}, "description": "Проверка успешной авторизации и выхода из системы", "steps": [{"name": "Переход на страницу логина", "status": "passed", "start": 1741679324468, "stop": 1741679326400}, {"name": "Ввод учетных данных и вход", "status": "passed", "start": 1741679326400, "stop": 1741679327719}, {"name": "Проверка успешной авторизации", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Timeout 10000ms exceeded.\n=========================== logs ===========================\nwaiting for navigation to \"**https://liner.dstepanyuk.dev.smte.am/office/*\" until 'load'\n============================================================\n", "trace": "  File \"E:\\automation\\tests\\test_auth.py\", line 23, in test_successful_login_and_logout\n    page.wait_for_url(f\"**{expected_url}*\", timeout=10000)\n  File \"E:\\automation\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9161, in wait_for_url\n    self._sync(\n  File \"E:\\automation\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"E:\\automation\\.venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 575, in wait_for_url\n    return await self._main_frame.wait_for_url(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\automation\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 233, in wait_for_url\n    async with self.expect_navigation(\n  File \"E:\\automation\\.venv\\Lib\\site-packages\\playwright\\_impl\\_event_context_manager.py\", line 33, in __aexit__\n    await self._future\n  File \"E:\\automation\\.venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 207, in continuation\n    event = await waiter.result()\n            ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1741679327719, "stop": 1741679337755}], "start": 1741679324468, "stop": 1741679337785, "uuid": "3002ee81-bbfc-420f-a11d-af8050aea2de", "historyId": "ae68f5a78a693dc1d0419302ec8d8402", "testCaseId": "ae68f5a78a693dc1d0419302ec8d8402", "fullName": "tests.test_auth.TestAuthentication#test_successful_login_and_logout", "labels": [{"name": "feature", "value": "Authentication"}, {"name": "story", "value": "Successful login and logout"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-US86AEC"}, {"name": "thread", "value": "14460-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}